# site settings
title: Sijoon Lee
subtitle: Portfolio
email: shijoonlee@gmail.com
description: Studies, Practices and Projects</br> 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Kingston
state: Ontario
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sijoonlee/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/sijoon-lee-a10137175/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
